definitions:
  config:
    /hst:hst/hst:hosts/prod-carpart-kz:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:cmslocation: http://localhost:8080/cms
      hst:defaultport: 8080
